stages:
  - linting
  - pages

linting:
  stage: linting
  image: node:lts
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn lint

pages:
  stage: pages
  image: node:lts
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
    - public
  only:
    - main




