stages:
  - linting
  - deploy

linting:
  stage: linting
  image: node:14.15.1
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn lint

deploy:
  stage: deploy
  image: node:14.15.1
  script:
    - yarn install
    - yarn build
  artifacts:
    paths:
    - public
  only:
    - main




