stages:
  - linting
  - deploy

linting:
  stage: linting
  image: node:14.15.1
  cache:
    paths:
    - node_modules/
  script:
    - npm install
    - npm run-script lint

deploy:
  stage: deploy
  image: node:14.15.1
  script:
    - npm install
    - npm run-script build
  artifacts:
    paths:
    - public
  only:
    - main




