stages:
  - linting
  - deploy

linting:
  stage: linting
  image: node:lts
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn lint

deploy:
  stage: deploy
  image: node:lts
#  cache:
#    paths:
#      - node_modules/
  script:
    - yarn cache verify
    - yarn install
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
    - public
  only:
    - main




