stages:
  - linting
  - deploy

linting:
  stage: linting
  image: node:14.15.1
  cache:
    paths:
    - node_modules/
  script:
    - yarn install
    - yarn lint

deploy:
  stage: deploy
  image: node:14.15.1
  cache:
    paths:
      - node_modules/
  script:
    - yarn install
    - rm -rf public
    - yarn build
  artifacts:
    expire_in: 1 day
    paths:
    - public
  only:
    - main




